[versions]
kotlin = "2.3.21"
kotlinx-coroutines = "1.8.1"
kotlinx-serialization = "1.6.3"
clikt = "4.3.0"
mordant = "2.6.0"
exposed = "0.50.1"
sqlite-jdbc = "3.45.3.0"
bonede-core = "0.23.0"
bonede-java = "0.23.5"
bonede-kotlin = "0.3.8.1"
bonede-rust = "0.21.2"
bonede-typescript = "0.23.2"
bonede-go = "0.23.3"
bonede-c = "0.23.2"
bonede-cpp = "0.23.4"
bonede-csharp = "0.23.1"
bonede-javascript = "0.23.1"
bonede-css = "0.23.1"
graalvm = "0.9.28"
jline = "3.26.1"
jansi = "2.4.1"
okio = "3.9.0"


[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version.ref = "clikt" }
mordant = { group = "com.github.ajalt.mordant", name = "mordant", version.ref = "mordant" }
exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed" }
exposed-dao = { group = "org.jetbrains.exposed", name = "exposed-dao", version.ref = "exposed" }
exposed-jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version.ref = "exposed" }
sqlite-jdbc = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite-jdbc" }
tree-sitter = { group = "io.github.bonede", name = "tree-sitter", version.ref = "bonede-core" }
tree-sitter-java = { group = "io.github.bonede", name = "tree-sitter-java", version.ref = "bonede-java" }
tree-sitter-kotlin = { group = "io.github.bonede", name = "tree-sitter-kotlin", version.ref = "bonede-kotlin" }
tree-sitter-rust = { group = "io.github.bonede", name = "tree-sitter-rust", version.ref = "bonede-rust" }
tree-sitter-typescript = { group = "io.github.bonede", name = "tree-sitter-typescript", version.ref = "bonede-typescript" }
tree-sitter-go = { group = "io.github.bonede", name = "tree-sitter-go", version.ref = "bonede-go" }
tree-sitter-c = { group = "io.github.bonede", name = "tree-sitter-c", version.ref = "bonede-c" }
tree-sitter-cpp = { group = "io.github.bonede", name = "tree-sitter-cpp", version.ref = "bonede-cpp" }
tree-sitter-c-sharp = { group = "io.github.bonede", name = "tree-sitter-c-sharp", version.ref = "bonede-csharp" }
tree-sitter-javascript = { group = "io.github.bonede", name = "tree-sitter-javascript", version.ref = "bonede-javascript" }
tree-sitter-css = { group = "io.github.bonede", name = "tree-sitter-css", version.ref = "bonede-css" }
jline = { group = "org.jline", name = "jline", version.ref = "jline" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version.ref = "jansi" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm" }
