package dev.ajithgoveas.kindex.cli.commands

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.arguments.optional
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.mordant.rendering.TextColors.green
import com.github.ajalt.mordant.rendering.TextColors.red
import com.github.ajalt.mordant.terminal.Terminal
import dev.ajithgoveas.kindex.core.io.MPFile
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.SYSTEM

class HookCommand : CliktCommand(name = "hook", help = "Manage Git hooks for automatic background indexing") {
    private val action by argument(help = "Action: 'install' or 'uninstall'")
    private val dirArg by argument(name = "dir", help = "Target project directory").optional()
    private val dirOpt by option("-d", "--dir", help = "Target project directory")

    override fun run() {
        val t = Terminal()
        val directory = dirOpt ?: dirArg ?: "."
        val targetDir = MPFile(directory)
        val gitDir = MPFile("${targetDir.path}/.git")

        if (!gitDir.exists || !gitDir.isDirectory) {
            t.println(red("Error: '${targetDir.absolutePath}' is not a Git repository (missing .git directory)."))
            return
        }

        val hooksDir = MPFile("${gitDir.path}/hooks")
        if (!hooksDir.exists) {
            FileSystem.SYSTEM.createDirectories(hooksDir.path.toPath())
        }

        val postCommitPath = "${hooksDir.path}/post-commit".toPath()
        val postCheckoutPath = "${hooksDir.path}/post-checkout".toPath()

        val hookMarkerStart = "# --- KINDEX GIT HOOK START ---"
        val hookMarkerEnd = "# --- KINDEX GIT HOOK END ---"

        val hookScriptContent = """
            |$hookMarkerStart
            |# Auto-generated by KIndex. Synchronizes the code graph on git events.
            |if [ -f "./kindex-cli/build/install/kindex-cli/bin/kindex-cli" ]; then
            |    ./kindex-cli/build/install/kindex-cli/bin/kindex-cli scan . --quiet
            |elif [ -f "./gradlew" ]; then
            |    ./gradlew :kindex-cli:jvmRun --args="scan . --quiet" --quiet
            |elif command -v kindex >/dev/null 2>&1; then
            |    kindex scan . --quiet
            |fi
            |$hookMarkerEnd
        """.trimMargin()

        when (action.lowercase()) {
            "install" -> {
                installHook(postCommitPath, hookMarkerStart, hookMarkerEnd, hookScriptContent)
                installHook(postCheckoutPath, hookMarkerStart, hookMarkerEnd, hookScriptContent)
                t.println(green("✓ Successfully installed KIndex Git hooks (post-commit, post-checkout) in ${hooksDir.path}"))
            }
            "uninstall" -> {
                uninstallHook(postCommitPath, hookMarkerStart, hookMarkerEnd)
                uninstallHook(postCheckoutPath, hookMarkerStart, hookMarkerEnd)
                t.println(green("✓ Successfully uninstalled KIndex Git hooks from ${hooksDir.path}"))
            }
            else -> {
                t.println(red("Unknown action '$action'. Use 'install' or 'uninstall'."))
            }
        }
    }

    private fun installHook(
        hookPath: okio.Path,
        markerStart: String,
        markerEnd: String,
        scriptContent: String
    ) {
        val existingContent = if (FileSystem.SYSTEM.exists(hookPath)) {
            FileSystem.SYSTEM.read(hookPath) { readUtf8() }
        } else {
            "#!/bin/sh\n"
        }

        val cleanedContent = removeKIndexBlock(existingContent, markerStart, markerEnd)
        val newContent = if (cleanedContent.trim().isEmpty()) {
            "#!/bin/sh\n\n$scriptContent\n"
        } else {
            "${cleanedContent.trimEnd()}\n\n$scriptContent\n"
        }

        FileSystem.SYSTEM.write(hookPath) {
            writeUtf8(newContent)
        }
    }

    private fun uninstallHook(
        hookPath: okio.Path,
        markerStart: String,
        markerEnd: String
    ) {
        if (!FileSystem.SYSTEM.exists(hookPath)) return
        val existingContent = FileSystem.SYSTEM.read(hookPath) { readUtf8() }
        val cleanedContent = removeKIndexBlock(existingContent, markerStart, markerEnd).trim()

        if (cleanedContent.isEmpty() || cleanedContent == "#!/bin/sh") {
            FileSystem.SYSTEM.delete(hookPath)
        } else {
            FileSystem.SYSTEM.write(hookPath) {
                writeUtf8("$cleanedContent\n")
            }
        }
    }

    private fun removeKIndexBlock(content: String, markerStart: String, markerEnd: String): String {
        val lines = content.lines()
        val result = mutableListOf<String>()
        var insideBlock = false

        for (line in lines) {
            if (line.trim() == markerStart) {
                insideBlock = true
                continue
            }
            if (line.trim() == markerEnd) {
                insideBlock = false
                continue
            }
            if (!insideBlock) {
                result.add(line)
            }
        }
        return result.joinToString("\n")
    }
}
